/*
 * This source file was generated by the Gradle 'init' task
 */
package uielements;


import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.stage.Stage;


public class LoginUI {


/**
 * loginLabel เป็นการเเสดงข้อความเขียนว่า  กรุณาล็อคอิน
 * nameLabel เป็นการเเสดงข้อความเขียนว่า UserName
 * usernameField เป็นการใส่ข้อความที่ต้องการสร้าง UserName
 * passwordLabel เป็นการเเสดงข้อความเขียนว่า PassWord
 * passwordField เป็นการใส่ข้อความที่ต้องการสร้าง PassWord
 * loginButton เป็นปุ่มสำหรับใช้งาน ในการล็อคอิน
 * creatAccountsButton เป็นปุ่มสำหรับใช้งาน ในการสร้างรหัส
 * 
 */




    public LoginUI(Stage primaryStage){
        // สร้าง Container ไว้ใส่ UI 
        VBox root = new VBox(10);
        root.setStyle("-fx-padding: 20;");

        // สร้าง องค์ประกอบใน UI
        // ถ้าสำคัญให้ .setid("ตั้งชื่อ") เพื่อไว้ทำ Testcase ด้วย 
        Label loginLabel = new Label("กรุณาล็อคอิน");
        Label nameLabel = new Label("UserName");
        TextField usernameField = new TextField("");
        Label passwordLabel = new Label("PassWord");
        TextField passwordField = new TextField("");
        Label messageLabel = new Label();
       
        Button loginButton = new Button("ปุ่ม (Button): ล็อคอิน");
        
        Button creatAccountsButton = new Button("ปุ่ม (Button): สร้างรหัส");


        // ตั้ง Action เมื่อผู้ใช้ทำ...กับ UI เช่นคลิกปุ่ม
        
       creatAccountsButton.setOnAction(e -> new CreatAcountsUI(primaryStage));


        /**
         * เมธอด ตรวจสอบว่ามี User ตรงกับข้อมูลที่กรอกไหม
         */
        loginButton.setOnAction(e -> {
        User user = Database.authenticate(usernameField.getText(), passwordField.getText());
        if (user != null) new BookingUI(primaryStage);
        else messageLabel.setText("Invalid credentials.");
    });
   
        

       

        /**
         * เพิ่มทุกอยุ่างลง VBox Container เพื่อจัดวางลง
         */
        root.getChildren().addAll(loginLabel,nameLabel,usernameField,passwordLabel,passwordField,loginButton,creatAccountsButton,  messageLabel);
        

        /**
         * ตั้งขนาดหน้าจอและ Show VBox
         */
        Scene scene = new Scene(root, 400, 600);
        primaryStage.setTitle("JavaFX UI Components");
        primaryStage.setScene(scene);
        primaryStage.show();
    }

}
